### ISSUE TITLE
Window to tall

### ISSUE THREAD

**Issue by scootergrisen** [blockattack/blockattack-game#11]
On screen with 768 pixels height i can't see the whole window content at the same time.
In GNOME there are a top panel taking up some space plus the windows titel bar.

**Comment by sago007** [comment]
The master version does allow scaling but it does not look particular well. Fonts are the big problem, although it was changed it still does not look particular well. 
I have started on a more right way to handle scaling. It the progress can be tested with "--no-auto-scale".

**Comment by sago007** [comment]
I believe the resize ability in 2.3.0 should satisfy.
