### ISSUE TITLE
Font is not so readable

### ISSUE THREAD

**Issue by scootergrisen** [blockattack/blockattack-game#12]
The font choice and color and placement could be better so the text was easier to read.

**Comment by sago007** [comment]
Are you talking about 2.0.1 or the master version?
I changed the menu font to FreeSerif in the menu some time ago (commit 72383a9e4333ecc1699c17fef457b6ac9bc741a8) to make it easier to read.

**Comment by scootergrisen** [comment]
2.0.1 like the screenshot:
https://raw.githubusercontent.com/blockattack/blockattack-game/master/source/misc/screenshots/screen_shot_2016_01_19.png

Maybe use outline to make it more clear that way the background dont matter so much.
By outline i mean when the font have like an 1 px edge of other color.
So the font might be white but the outline is black.

**Comment by sago007** [comment]
The font should be much more readable now.
Version 2.3.0: https://blockattack.net/images/screenshots/blockattack-2.3.0-1.png
I had to write a new font handling to support outlining.

However I consider this closed.
