### ISSUE TITLE
Add ability to set initial starting speed for endless mode

### ISSUE THREAD

**Issue by mygithubcomments2017** [blockattack/blockattack-game#16]
E.g. it's boring to start on speed 1 if you are experienced.

**Comment by sago007** [comment]
This would properly need a submenu after choosing endless where you could choose between: Speed 1, 10, 20 etc.
High scores would need to be recorded separately for each.

**Comment by sago007** [comment]
Version 2.4.0 now has the option for picking different speeds for endless mode.
