### ISSUE TITLE
Minor Typos

### ISSUE THREAD

**Issue by iwanPlays** [blockattack/blockattack-game#19]
https://blockattack.net/download/

writes "GitGub" and "Github" instead of "GitHub" at two points. No biggie.

![image](https://user-images.githubusercontent.com/25465450/61169681-a5e1e880-a560-11e9-9167-1bc19bb28509.png)

**Comment by sago007** [comment]
Thank you!
This has now been corrected. CloudForge may serve a cached version for some time.
