### ISSUE TITLE
Issue with gamepad

### ISSUE THREAD

**Issue by poVoq** [blockattack/blockattack-game#20]
I have a USB XBOX360 pad connected to my Linux PC that works great with other games, but in Block Attack it does not seem to get recognized at all.

**Comment by sago007** [comment]
Xbox360 USB pad has been tested and is expected to work. It does work for me. Which distribution are you using? Have you compiled yourself or are you using a precompiled version?

One thing to be aware of is that the game only scans for gamepads at start-up. It is not possible to attach a gamepad while the game is running.

**Comment by poVoq** [comment]
Yes, that was the issue. When starting with it it works. I have a special setup that involves switching gamepads, thus this cause the problem. Maybe a menu entry to rescan for gamepads would help?
