### ISSUE TITLE
320x240 screens

### ISSUE THREAD

**Issue by glebm** [blockattack/blockattack-game#22]
I've managed to build this for the RG350 handheld (https://github.com/tonyjih/RG350_buildroot/pull/36)

Everything works, except the fonts are unreadable:

![IMG_20191211_113122](https://user-images.githubusercontent.com/216339/70618113-fc377e00-1c09-11ea-825f-3f8551deb83e.JPG)

**Comment by sago007** [comment]
When I started building BlockAttack I was frustrated by all the 640x480 games of the time. Which is why it was coded with a targeted minimum resolution of 1024x768.

It wasn't until recently that you could go less than 768p but it is unlikely that anything will be done about low resolution targets.
