### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by sanchez-gayatri** [blockattack/blockattack-game#32]
Hello
I have done a Swedish translation of Block Attack. See the attached file. Thanks for your work.

Best regards,
Sanchez

[sv.po.tar.gz](https://github.com/blockattack/blockattack-game/files/9034184/sv.po.tar.gz)

**Comment by sago007** [comment]
Thank you!

I have added it to the development branch and it will be available in 2.9.0+.
