### ISSUE TITLE
Man page improvement for NAME section

### ISSUE THREAD

**Issue by apoleon** [blockattack/blockattack-game#7]
The NAME section of blockattack's man page currently uses a generic description for the game. I think it would be a (minor) improvement if the NAME section would be changed from

blockattack \- manual page for blockattack 2.0.1
to
blockattack \- a puzzle game inspired by Tetris Attack

This minor issue was found with Lintian, a Debian package checker.
https://lintian.debian.org/tags/manpage-has-bad-whatis-entry.html

I'm attaching a patch.

From: Markus Koschany <apo@debian.org>
Date: Tue, 4 Oct 2016 17:00:07 +0200
Subject: bad whatis entry

---
 man/blockattack.man | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/man/blockattack.man b/man/blockattack.man
index 27de09e..3d9f81e 100644
--- a/man/blockattack.man
+++ b/man/blockattack.man
@@ -1,7 +1,7 @@
 .\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.3.
 .TH BLOCKATTACK "6" "October 2016" "blockattack 2.0.1" "Games"
 .SH NAME
-blockattack \- manual page for blockattack 2.0.1
+blockattack \- a puzzle game inspired by Tetris Attack
 .SH SYNOPSIS
 .B blockattack
 [\fI\,OPTION\/\fR]...

**Comment by sago007** [comment]
Thank you. I have added
`--name="a puzzle game inspired by Tetris Attack"` to the help2man command.
This should close the issue (and Github apparently already closed it the moment it saw a commit with the issue and the word close).
